apiVersion: v1
kind: Service
metadata:
  labels:
    type: application
    app: credits-competition-view
  name: credits-competition-view
  namespace: credits-competition
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: credits-competition-view
  type: ClusterIP
status:
  loadBalancer: {}
