apiVersion: v1
kind: Service
metadata:
  labels:
    type: application
    app: credits-competition-web
  name: credits-competition-web
  namespace: credits-competition
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: credits-competition-web
  type: ClusterIP
status:
  loadBalancer: {}
