apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    type: application
  name: credits-competition-ingress
  namespace: credits-competition
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: credits-competition-web
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: credits-competition-view
            port:
              number: 80